[package]
name = "seele"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
anyhow = "1.0.66"
async-channel = "1.8.0"
async-recursion = "1.0.0"
async-trait = "0.1.59"
bytes = "1.3.0"
chrono = { version = "0.4.23", features = ["serde"] }
config = "0.13.3"
dbus = "0.9.7"
duct = "0.13.6"
either = "1.8.0"
ellipse = "0.2.0"
futures-util = "0.3.25"
http = "0.2.8"
http-cache = { version = "0.7.2", default-features = false, features = ["manager-moka"] }
http-cache-reqwest = "0.5.2"
hyper = { version = "0.14.23", features = ["server", "stream"] }
indexmap = { version = "1.9.2", features = ["serde-1"] }
libcgroups = "0.0.4"
moka = { version = "0.9.6", features = ["future"] }
nano-id = { version = "0.3.0", features = ["base62"] }
nix = "0.26.2"
num_cpus = "1.15.0"
once_cell = "1.16.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["metrics"] }
quick-js = { version = "0.4.1", features = ["patched"] }
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["stream"] }
reqwest-middleware = "0.2.0"
ring-channel = "0.11.0"
serde = { version = "1.0.149", features = ["derive", "rc"] }
serde_json = "1.0.91"
serde_yaml = "0.9.15"
shell-words = "1.1.0"
systemd = "0.10.0"
thread_local = "1.1.4"
tokio = { version = "1", features = ["full"] }
tokio-graceful-shutdown = "0.11.1"
tokio-util = { version = "0.7.4", features = ["io"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = "0.3.16"
triggered = "0.1.2"
users = "0.11.0"

[dev-dependencies]
insta = { version = "1.23.0", features = ["glob", "redactions", "ron"] }
rand = { version = "0.8.5" }
