[package]
name = "seele"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"
lto = true

[dependencies]
anyhow = "1.0.66"
async-channel = "1.8.0"
async-trait = "0.1.59"
config = "0.13.3"
once_cell = "1.16.0"
serde = { version = "1.0.149", features = ["derive", "rc"] }
tokio = { version = "1", features = ["full"] }
tokio-graceful-shutdown = "0.11.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
