[package]
name = "seele"
version = "0.2.0"
edition = "2021"

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
anyhow = "1.0"
async-recursion = "1.0"
async-trait = "0.1"
base64 = "0.21"
bincode = "2.0.0-rc.3"
bytes = "1.3"
chrono = { version = "0.4", features = ["serde"] }
config = "0.14"
dbus = "0.9"
duct = "0.13"
either = "1.8"
ellipse = "0.2"
futures-util = "0.3"
http = "1.0"
http-cache = { version = "0.18", default-features = false, features = ["manager-moka"] }
http-cache-reqwest = "0.13"
hyper = { version = "=0.14.24", features = ["server", "stream"] }
indexmap = { version = "2.2", features = ["serde"] }
lapin = "2.1"
libcgroups = "0.3"
moka = { version = "0.12", features = ["future", "sync"] }
nano-id = { version = "0.3", features = ["base62"] }
nix = { version = "0.27", features = ["mount", "hostname"] }
num_cpus = "1.15"
once_cell = "1.16"
opentelemetry = { version = "=0.18.0", features = ["rt-tokio", "metrics", "trace"] }
opentelemetry-otlp = { version = "=0.11.0", features = ["metrics"] }
quick-js = { version = "0.4", features = ["patched"] }
regex = "1.7"
reqwest = { version = "0.11", features = ["stream"] }
reqwest-middleware = "0.2"
ring-channel = "0.12"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml = "0.9"
sha2 = "0.10"
shell-words = "1.1"
systemd = "0.10"
thread_local = "1.1"
tokio = { version = "1", features = ["full"] }
tokio-graceful-shutdown = "0.14"
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1"
tracing-opentelemetry = "=0.18.0"
tracing-subscriber = "0.3"
triggered = "0.1"
url = { version = "2.3", features = ["serde"] }
users = "0.11"

[dev-dependencies]
insta = { version = "1.23", features = ["glob", "redactions", "ron"] }
map-macro = "0.3"
rand = { version = "0.8" }
