[package]
name = "seele"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"
lto = true

[dependencies]
anyhow = "1.0.66"
async-channel = "1.8.0"
async-recursion = "1.0.0"
async-trait = "0.1.59"
config = "0.13.3"
futures-util = "0.3.25"
indexmap = { version = "1.9.2", features = ["serde-1"] }
nano-id = { version = "0.3.0", features = ["base62"] }
once_cell = "1.16.0"
serde = { version = "1.0.149", features = ["derive", "rc"] }
serde_yaml = "0.9.15"
tokio = { version = "1", features = ["full"] }
tokio-graceful-shutdown = "0.11.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dev-dependencies]
insta = { version = "1.23.0", features = ["glob", "redactions"] }
