name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
            GIT_NAME=${{ github.ref_name }}
          tags: |
            ghcr.io/darkyzhou/seele:latest
            ghcr.io/darkyzhou/seele:${{ github.sha }}
            ghcr.io/darkyzhou/seele:${{ github.ref_name }}
